[package]
name = "gbackup-rs"
version = "0.2.0"
authors = ["Nikola Dipanov <nikola.djipanov@gmail.com>"]
edition = "2018"
description = "Fast and configurable CLI tool to back-up your GMail data"
license = "MIT"
keywords = ["gmail", "backup", "cli"]
categories = ["command-line-utilities"]
repository = "https://github.com/djipko/gbackup-rs/"

[dependencies]
chrono = "0.4.43"
clap = "4.5.59"
imap = "2.4.1"
mailparse = "0.16.1"
native-tls = "0.2.16"
rusqlite = "0.38.0"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
threadpool = "1.8.1"
toml = "1.0.2"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
